### ISSUE TITLE
Wiki is wrong or the config is broken.

### ISSUE THREAD

**Issue by KaneHart** [nguyenquyhy/Sponge-Discord#10]
Launched discord plugin 2.0 and this my config:
http://pastebin.com/cXgUJYVa

I don't have token for a bot anywhere.

**Comment by rockmacaca** [comment]
You can just `botToken` entry in yourself, and it will work. It looks like there wasn't a default value defined for it in the config classes, so I think it's a simple fix.

**Comment by nguyenquyhy** [comment]
Yes this is a mistake, and fixed in the next version.
