### ISSUE TITLE
Don't show server-related Discord messages in the Minecraft chat

### ISSUE THREAD

**Issue by rockmacaca** [nguyenquyhy/Sponge-Discord#11]
This should a reasonable feature to have, mostly because messages such as "_%s just joined the server_" end up duplicated after the native message, and they're not formatted in correctly.

It might be a good idea to generalize the implementation to blacklisting certain users/other bots from showing up. Especially for certain bots, it would help keep the chat Minecraft-side cleaner.

**Comment by nguyenquyhy** [comment]
I don't really understand this issue? Are you saying that the message "%s just joined the server" is showing up in Minecraft? If so, that sounds like a bug, please provide the plugin version you are using.
If you don't want to show any message in Discord, just remove the template in the config.

**Comment by rockmacaca** [comment]
No it's not really a bug, it's more of room for improvement. Currently, the markdown-formatted message that the discord bot/account sends to discord is _also_ shown in minecraft
![image](https://cloud.githubusercontent.com/assets/4993980/20049957/78b6709e-a494-11e6-8d80-69e01dc3ca3e.png)

It isn't necessary for those kinds of messages to show up in the MC chat since it already prints that native player join message right before. Also, it prints the raw markdown string, which doesn't look great.

**Comment by nguyenquyhy** [comment]
This is not the intended behavior. Please try to use the latest version and let me know if it still happens. 😄

**Comment by Mohron** [comment]
This is in the latest version but I think you already figured that out.

**Comment by Vankka2** [comment]
My fork prevents this from happening if intrested https://github.com/Vankka2/Sponge-Discord

But backup your config there is a new line added to that (https://github.com/Vankka2/Sponge-Discord/blob/master/config.json)

**Comment by Mohron** [comment]
@Vankka2 You should make a PR :)

**Comment by Vankka2** [comment]
:D maybe
