### ISSUE TITLE
Escape formatting characters in usernames and chat

### ISSUE THREAD

**Issue by rockmacaca** [nguyenquyhy/Sponge-Discord#12]
I noticed this with usernames with underscores causing the default server disconnect message template to italicize incorrectly.

I think formatting in the message text itself should also be escaped - it could just transform §l, §o etc. into markdown if there's a chat plugin installed doing that.

**Comment by nguyenquyhy** [comment]
Which version are you using? I believe I already handle underscore in 2.0.0 version. I will add support for &l and &o later.

**Comment by rockmacaca** [comment]
I am on 2.0.0. Chat messages to Discord seem to still send an unescaped underscore in the middle. It's only affected by server join and leave messages by default since the backticks used around the usernames will automatically escape everything between them.

So the markdown `_cheese_nip just joined the server_` gets (incorrectly) rendered as  
cheese _nip just joined the server_  

while `` `cheese_nip` test message`` is still ok:  
`cheese_nip` test message

**Comment by nguyenquyhy** [comment]
Please try 2.1.0 version 😄 . I missed that in 2.0.0.
