### ISSUE TITLE
Cant send ClientConnectionEvent

### ISSUE THREAD

**Issue by Tencao** [nguyenquyhy/Sponge-Discord#13]
> [Server thread/ERROR] [Sponge/]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=com.nguyenquyhy.spongediscord, name=Discord Bridge, version=2.0.0, description=A Sponge plugin to connect your Minecraft server with Discord, authors=[Hy], source=C:\Users\Administrator\AppData\Local\CubeCoders\AMP\Instances\1-TCR\Minecraft\mods\plugins\Sponge-Discord-2.0.0-all.jar}
> java.lang.NullPointerException
>     at com.nguyenquyhy.spongediscord.listeners.ClientConnectionListener.onJoin(ClientConnectionListener.java:42) ~[ClientConnectionListener.class:?]
>     at org.spongepowered.common.event.listener.JoinListener_ClientConnectionListener_onJoin60.handle(Unknown Source) ~[?:?]
>     at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2107-6.0.0-BETA-1843]
>     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:356) [SpongeModEventManager.class:1.10.2-2107-6.0.0-BETA-1843]
>     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:339) [SpongeModEventManager.class:1.10.2-2107-6.0.0-BETA-1843]
>     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:384) [SpongeModEventManager.class:1.10.2-2107-6.0.0-BETA-1843]
>     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:369) [SpongeModEventManager.class:1.10.2-2107-6.0.0-BETA-1843]
>     at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140) [SpongeImpl.class:1.10.2-2107-6.0.0-BETA-1843]
>     at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:401) [mp.class:?]
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
>     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
>     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
>     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
>     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>     at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by Tencao** [comment]
Just gonna say that the issue was resolved after double checking the channel id, however I want to leave this open to request a better error message than this.

**Comment by nguyenquyhy** [comment]
Strange. I thought that this was due to incorrect bot token instead of channel ID. I have improved this anyway.
