### ISSUE TITLE
Discord Join Messages sent to Minecraft

### ISSUE THREAD

**Issue by Mohron** [nguyenquyhy/Sponge-Discord#16]
The join messages sent to discord also show up in Minecraft with the discord formatting/escaping.  This looks really bad and was not the original behavior IIRC.  Personally, I don't need this plugin to send join messages in game at all and most servers will also likely have another plugin taking care of the MC join message. 

Can you please fix the formatting and give us the option to shut of the join message on a specific side?

**Comment by nguyenquyhy** [comment]
Please see #11
