### ISSUE TITLE
Add configurable Filter

### ISSUE THREAD

**Issue by Mohron** [nguyenquyhy/Sponge-Discord#17]
As you know, currently the discord api doesn't support slash commands for bots. Since bots are forced to use other characters to designate commands, it would be helpful to be able to filter them from being sent to minecraft.

Ex: commandFilter:"!" # filters messages that begin with the character(s) designated here

**Comment by nguyenquyhy** [comment]
Not really, bot can response to any message. Using ! for command is just a recommendation. Maybe I'll add a prefix blacklist though.

**Comment by Mohron** [comment]
I'm not talking about just your bot. We have many discord bot functions on our discord. Basically if someone sends a message that's a bot command, I don't want it to be sent to mc. Making it a configurable blacklist will support the most people. All our bots use "!" atm, both other people may have different needs and possibly multiple prefixes.

**Comment by Vankka2** [comment]
I added this feature to my fork :) https://github.com/Vankka2/Sponge-Discord 

Remember to backup your config (there is a new option https://github.com/Vankka2/Sponge-Discord/blob/master/config.json)

**Comment by nguyenquyhy** [comment]
Merged. The feature is coming in next update.
