### ISSUE TITLE
I suspect that Sponge-Discord is sending a character to the channel that can't seem to be parsed correctly by  DiscordSRV on a spigot server.

### ISSUE THREAD

**Issue by PsychoNavigator** [nguyenquyhy/Sponge-Discord#18]
I am using a single channel on discord with two separate bots. 

For some reason, most all the chat and server start (but not stop) notifications have an ☒ character after it when sent from my FTB server using Sponge-Discord to  Discord channel, and relayed over to my spigot server using DiscordSRV.

The character does not show up anywhere else, but the fact that its showing up on everything but the server stop notifications tells me that it's likely something in the formatting for Sponge-Discord that is causing the issue possibly.

Chatting from the discord channel also confirms that this isn't likely to be caused by DiscordSRV beyond Sponge-Discord sending a character that Discord doesn't even bother trying to parse, but DiscordSRV does and fails.

Image for reference.

http://i.imgur.com/0ECXr81.png

**Comment by nguyenquyhy** [comment]
This is expected. It is a way for Discord Bridge to distinguish message from itself to that it will not send those back to Minecraft. 😄

**Comment by PsychoNavigator** [comment]
I don't have that issue with DiscordSRV sending messages the other way, though.

**Comment by nguyenquyhy** [comment]
There is a new config in the next version to choose between using special character or simply ignore all messages from the bot.

**Comment by PsychoNavigator** [comment]
I'll take a look! Thank you!

**Comment by nguyenquyhy** [comment]
I changed my mind. You won't need the config anymore 😄 . You simply won't see the special character in 2.2.0. I am doing some final test for the update and will release it soon.
