### ISSUE TITLE
I have this error when I use /discord default login {email} {PW}

### ISSUE THREAD

**Issue by dungeonmaster372** [nguyenquyhy/Sponge-Discord#2]
Attached is the error in console I am getting I have all the correct login stuff and I have the correct invite code as well

I also get this error:

When using /discord login {My Email} {My PW}

Cant get cached token

[Sponge-Discord Issue log.txt](https://github.com/nguyenquyhy/Sponge-Discord/files/138945/Sponge-Discord.Issue.log.txt)

I am currently using mc 1.8.9 forge version 1732 spongeforge (for 1732)

**Comment by PandawanFr** [comment]
Yeah, I get "Cannot remove cached token"

**Comment by nguyenquyhy** [comment]
Please try again with 2.0.0 release and let me know if this still happens.
https://github.com/nguyenquyhy/Sponge-Discord/releases/tag/v2.0.0
