### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by Darktilldawn** [nguyenquyhy/Sponge-Discord#3]
Still having the error of Discord to Minecraft chat being displayed in game. Only the prefix I've set up in the configs is showing in chat.

Upon logging into the server while previously logged in to discord. Meaning I have a token and the accounts linked, when i login to the server, my console get's spammed with permission errors from the Pixelmon Discord channel saying I do not have the proper perms. Is there a way you can disable that check on login through config or something?

**Comment by nguyenquyhy** [comment]
The latest release should fix this problem :).
