### ISSUE TITLE
The bot dies after a while

### ISSUE THREAD

**Issue by inklit** [nguyenquyhy/Sponge-Discord#4]
> [22:39:08] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@140f315f
> java.lang.NullPointerException
>         at com.nguyenquyhy.spongediscord.SpongeDiscord.onChat(SpongeDiscord.java:283) ~[SpongeDiscord.class:?]
>         at org.spongepowered.common.event.listener.ChatListener_SpongeDiscord_onChat21.handle(Unknown Source) ~[?:?]
>         at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1509]
>         at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1509]
>         at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:157) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1509]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:89) [EventBus.class:?]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:78) [EventBus.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$0(NetHandlerPlayServer.java:78) [lm.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:799) [lm.class:?]
>         at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
>         at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
>         at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1509]
>         at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

Once it dies, the default account no longer tranfers messages between the server and the channel.
If users logged into their own account, that works from MC->Discord, but no messages are sent back.

**Comment by nguyenquyhy** [comment]
Thanks for the report. I will try to add some reconnect mechanism soon.

**Comment by nguyenquyhy** [comment]
Automatically reconnection is now in 2.0.0 release. However, it might still fail if it cannot reconnect after a long time. In that case, you can use `/discord reload` to force reconnection.
