### ISSUE TITLE
403 accepting invite

### ISSUE THREAD

**Issue by bgsteiner** [nguyenquyhy/Sponge-Discord#6]
So it looks like the system that you are using to connect to channels in the latest version using the OAuth bot system does not work as bots cannot use the invite system. Otherwise the bot is abel to connect to discords api but is not able to connect to the server. I have tested this with several invites all being infinite invites.

`
24.07 23:12:20 [Server] WebSocketClient@1810509494-43/INFO [sx.blah.discord.Discord4J]: Connected to the Discord Websocket v4

24.07 23:12:20 [Server] WebSocketClient@1810509494-43/INFO [sx.blah.discord.Discord4J]: Connected to 0 guilds.

24.07 23:12:20 [Server] WebSocketClient@1810509494-43/INFO [com.nguyenquyhy.spongediscord]: Discord account minecraft-bot will be used for all unauthenticated users!

24.07 23:12:20 [Server] WebSocketClient@1810509494-43/INFO [com.nguyenquyhy.spongediscord]: Accepting channel invite for default account...

24.07 23:12:20 [Server] WebSocketClient@1810509494-43/ERROR [sx.blah.discord.Discord4J]: Received 403 forbidden error for url https://discordapp.com/api/invite/013DKLHWmzYwEez3s. If you believe this is a Discord4J error, report this!

24.07 23:12:20 [Server] WebSocketClient@1810509494-43/ERROR [com.nguyenquyhy.spongediscord]: Cannot accept invitation 013DKLHWmzYwEez3s
`

**Comment by nguyenquyhy** [comment]
Yes, bot cannot use the invitation. You will have to add the bot to the channel by yourself.

**Comment by bgsteiner** [comment]
How do you add the bot to the channel yourself if its not able to ist self.

**Comment by nguyenquyhy** [comment]
Here you go:
https://discordapp.com/developers/docs/topics/oauth2#adding-bots-to-guilds
