### ISSUE TITLE
Discord rank color not being shown ingame

### ISSUE THREAD

**Issue by Tencao** [nguyenquyhy/Sponge-Discord#74]
So according to the wiki, the discord rank is suppose to automatically convert the ranks color ingame, however it currently doesn't seem to work

**Comment by Mohron** [comment]
Discord allows you to use colors that Minecraft doesn't support.  Change your role colors in discord to match a valid [Minecraft Color](https://minecraft.gamepedia.com/Formatting_codes).

**Comment by Tencao** [comment]
Anyway to allow us to pre-define colors that minecraft cant auto set in a config file? It would be easier than trying to match the colors up perfectly.

Something like group: Admin, color :&9

**Comment by Mohron** [comment]
You have to either use MC colors or per role configuration to set the color.
https://github.com/nguyenquyhy/DiscordBridge/blob/master/examples/config-multiple.json#L37-L45

**Comment by Tencao** [comment]
Oh, I didn't realise it was already in, my bad. I'll close this then
