### ISSUE TITLE
[1.11.2][2.4.0] Bot won't post in channels under the new Category system

### ISSUE THREAD

**Issue by AzureDoom** [nguyenquyhy/Sponge-Discord#75]
Seems there was a change under the new Category system causing this stop working. It connects to the discord server just fine but I'm guessing the API changed for posting in the selected channel.

**Comment by GabbyLorelai** [comment]
I am also having this issue.
It tells me in the console that the Channel ID has changed.
I reuploaded the plugin, redid the config, and created a new discord bot, however I am still having issues.
Here is a link to the entire error : https://gist.github.com/GabbyLorelai/da899337b451dca4836a188f0e745b3c

I am using : 
DiscordBridge-2.4.0-all.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2637.jar
Pixelmon-1.10.2-5.1.2-universal.jar

There are also other mods and plugins, so if you'd like a full list, I can provide.

**Comment by unovalegends** [comment]
I am having the same issue

**Comment by Mohron** [comment]
Try this: https://github.com/DevOnTheRocks/DiscordBridge/releases/tag/v2.4.1

I was hoping Hy would get to merging this so I wouldn't have to link a build from my repo. Either way, if you're worried about my builds, I've been a contributor for quite some time and have had many PR's merged.
