### ISSUE TITLE
[Enchancement] More Discord Channels

### ISSUE THREAD

**Issue by Eufranio** [nguyenquyhy/Sponge-Discord#8]
Would be nice if you add a config to put more than one Discord Channel to be relayed to Minecraft. Kinda, i have a Staff channel and a General channel, i would like if i could receive in-game messages from Staff channel.

**Comment by nguyenquyhy** [comment]
Yes I am thinking about this too. My previous idea was to add more detailed config for channels. For example, channels for chat messages. Channels for join/leave messages. And now forward-only channels for staff announcement as well.

However, I don't want to make the config too complicated and scares all new users. Do you have any suggestion on a good format?

**Comment by Eufranio** [comment]
A new channels.conf file, pre-configured, that catches the IDs from the general config and make a link. If a experienced guy wants more channels, he would be able to add more channels in the config.
Would be nice a "playerlist" command too

**Comment by nguyenquyhy** [comment]
The feature is implemented in 2.0.0 release. Please try and let me know if that is what you want :).
https://github.com/nguyenquyhy/Sponge-Discord/releases/tag/v2.0.0
