### ISSUE TITLE
IllegalArguementException

### ISSUE THREAD

**Issue by Tencao** [nguyenquyhy/Sponge-Discord#9]
So I got this error when setting up discord, and I've trimmed down the log so you can get a clean look at the error.

> [Discord4JLogger:error433]: java.lang.IllegalArgumentException: No enum constant sx.blah.discord.handle.obj.Presences.DND
> [Discord4JLogger:error433]: 	at java.lang.Enum.valueOf(Unknown Source)
> [Discord4JLogger:error433]: 	at sx.blah.discord.handle.obj.Presences.valueOf(Presences.java:6)
> [Discord4JLogger:error433]: 	at sx.blah.discord.api.internal.DiscordUtils.getGuildFromJSON(DiscordUtils.java:246)
> [Discord4JLogger:error433]: 	at sx.blah.discord.api.internal.DiscordWS.guildCreate(DiscordWS.java:674)
> [Discord4JLogger:error433]: 	at sx.blah.discord.api.internal.DiscordWS.onMessage(DiscordWS.java:368)
> [Discord4JLogger:error433]: 	at sx.blah.discord.api.internal.DiscordWS.onMessage(DiscordWS.java:1062)
> [Discord4JLogger:error433]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [Discord4JLogger:error433]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [Discord4JLogger:error433]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [Discord4JLogger:error433]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onBinaryMessage(JettyAnnotatedEventDriver.java:124)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messageComplete(SimpleBinaryMessage.java:68)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onBinaryFrame(JettyAnnotatedEventDriver.java:116)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:157)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:367)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
> [Discord4JLogger:error433]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
> [Discord4JLogger:error433]: 	at java.lang.Thread.run(Unknown Source)

Sponge version - 1.10.2-2092-5.0.0-BETA-1770
Forge version - 1.10.2-12.18.1.2094

**Comment by nguyenquyhy** [comment]
Thank you for the log. I think I did not test with that sponge version. I will check and update soon.

**Comment by nguyenquyhy** [comment]
Please try again with the new 2.0.0 release and let me know if the issue still happen :).
https://github.com/nguyenquyhy/Sponge-Discord/releases/tag/v2.0.0
